// *** DO NOT EDIT THIS FILE FOR A COMP30950 ASSIGNMENT OR PROG EXAM ****

val scala3Version = "3.2.0"

lazy val root = project
  .in(file("."))
  .settings(
    name := "ProgExam2023",
    scalaVersion := scala3Version,
    libraryDependencies += "org.scalatest" %% "scalatest-funsuite" % "3.2.16" % "test"
  )